# agent/tools/__init__.py
from agent.tools.profile import get_garden_profile, update_garden_profile
from agent.tools.projects import (
    create_project, update_project, get_project, list_projects, 
    assign_bed_to_project, assign_container_to_project, 
    unassign_bed_from_project, unassign_container_from_project,
    add_plant_to_project, remove_plant_from_project, delete_project)
from agent.tools.beds_containers import (
    list_beds, update_bed,
    list_containers, add_container, update_container, remove_container,
    delete_bed
)
from agent.tools.plants import (
    add_plant, update_plant, remove_plant, list_plants,
    batch_add_plant_type, batch_update_plants, batch_remove_plants, list_batches,
    delete_plant, delete_batch)
from agent.tools.search import search_garden, list_by_location
from agent.tools.activity import (
    get_project_activity,
    get_plant_activity,
    get_bed_activity,
    get_container_activity,
    get_batch_activity,
    list_recent_activity,
)
from agent.tools.planning import (
    get_or_create_project_brief,
    update_project_brief,
    get_project_brief,
    assemble_planning_context,
    check_blocking_unknowns,
    list_candidate_locations,
    list_candidate_plant_material,
    save_project_proposal,
    list_project_proposals,
    accept_project_proposal,
    preview_project_schedule,
)
from agent.tools.tracker import (
    generate_project_tasks,
    regenerate_project_tasks,
    materialize_recurring_tasks,
    list_project_tasks,
    get_task,
    list_due_tasks,
    list_blocked_tasks,
    list_task_series,
    explain_task_blockers,
    start_task,
    complete_task,
    skip_task,
    defer_task,
    update_task,
    update_task_series,
)
from agent.tools.weather import (
    refresh_weather_snapshot,
    get_latest_weather_snapshot,
    list_weather_impacted_tasks,
    draft_weather_task_changes,
    approve_weather_task_changes,
)
from agent.tools.triage import (
    run_daily_triage,
    get_latest_triage_snapshot,
    list_triage_recommendations,
)
from agent.tools.care import (
    get_current_care_state,
    get_recent_care_history,
)
from agent.tools.incidents import (
    report_incident,
    draft_treatment_plan,
    get_treatment_plan,
    approve_treatment_plan,
    resolve_incident,
)

tools = [
    get_garden_profile,
    update_garden_profile,
    create_project,
    update_project,
    get_project,
    list_projects,
    assign_bed_to_project,
    assign_container_to_project,
    unassign_bed_from_project,
    unassign_container_from_project,
    add_plant_to_project,
    remove_plant_from_project,
    delete_project,
    list_beds,
    update_bed,
    list_containers,
    add_container,
    update_container,
    remove_container,
    delete_bed,
    add_plant,
    update_plant,
    remove_plant,
    list_plants,
    batch_add_plant_type,
    batch_update_plants,
    batch_remove_plants,
    list_batches,
    delete_plant,
    delete_batch,
    search_garden,
    list_by_location,
    get_project_activity,
    get_plant_activity,
    get_bed_activity,
    get_container_activity,
    get_batch_activity,
    list_recent_activity,
    get_or_create_project_brief,
    update_project_brief,
    get_project_brief,
    assemble_planning_context,
    check_blocking_unknowns,
    list_candidate_locations,
    list_candidate_plant_material,
    save_project_proposal,
    list_project_proposals,
    accept_project_proposal,
    preview_project_schedule,
    generate_project_tasks,
    regenerate_project_tasks,
    materialize_recurring_tasks,
    list_project_tasks,
    get_task,
    list_due_tasks,
    list_blocked_tasks,
    list_task_series,
    explain_task_blockers,
    start_task,
    complete_task,
    skip_task,
    defer_task,
    update_task,
    update_task_series,
    refresh_weather_snapshot,
    get_latest_weather_snapshot,
    list_weather_impacted_tasks,
    draft_weather_task_changes,
    approve_weather_task_changes,
    run_daily_triage,
    get_latest_triage_snapshot,
    list_triage_recommendations,
    get_current_care_state,
    get_recent_care_history,
    report_incident,
    draft_treatment_plan,
    get_treatment_plan,
    approve_treatment_plan,
    resolve_incident,
]
tools_by_name = {t.name: t for t in tools}
